apiVersion: v2
name: camunda-bpm-platform
description: |
  Community Helm chart for Camunda BPM Platform 7 (Engine, Tasklist, Cockpit, etc).
type: application
version: 7.6.7
appVersion: 7.x.x
keywords:
  - bpm
  - bpmn
  - camunda-bpm-platform
  - camunda-engine
  - dmn
  - process-engine
  - workflow
icon: https://docs.camunda.org/get-started/img/Camunda-Circle.svg
home: https://camunda.com
sources:
  - https://github.com/camunda-community-hub/camunda-helm/tree/main/charts/camunda-bpm-platform
  - https://github.com/camunda/docker-camunda-bpm-platform
  - https://github.com/camunda/camunda-bpm-platform
maintainers:
  - name: aabouzaid
    url: https://tech.aabouzaid.com
  - name: thecampagnards
    url: https://konstantinsidorenko.fr
annotations:
  artifacthub.io/links: |
    - name: Camunda BPM Platform 7 Helm chart
      url: https://github.com/camunda-community-hub/camunda-helm/tree/main/charts/camunda-bpm-platform
    - name: Camunda BPM Platform 7 Docker
      url: https://github.com/camunda/docker-camunda-bpm-platform
    - name: Camunda BPM Platform 7
      url: https://github.com/camunda/camunda-bpm-platform
  # This will be generated automatically by the release workflow.
  # https://github.com/camunda-community-hub/camunda-helm/blob/main/.github/workflows/release.yaml
  artifacthub.io/changes: |
