{{- $fullName := include "camunda-bpm-platform.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.general.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "camunda-bpm-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or (.Values.recreatePods) (.Values.podAnnotations) }}
      annotations:
        {{- if (.Values.recreatePods) }}
        created: {{ now }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "camunda-bpm-platform.selectorLabels" . | nindent 8 }}
        {{- include "camunda-bpm-platform.customLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "camunda-bpm-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 6 }}
      {{- end }}
      containers:
      {{- if .Values.extraContainers }}
      {{- with tpl (toYaml .Values.extraContainers) . }}
        {{ . | nindent 8 }}
      {{- end }}
      {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          {{ if .Values.image.command -}}
          command: {{ .Values.image.command }}
          {{- end }}
          {{- if .Values.image.args }}
          args:
            {{- toYaml .Values.image.args | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEBUG
              value: "{{ .Values.general.debug }}"
            - name: JMX_PROMETHEUS
              value: "{{ .Values.metrics.enabled }}"
            - name: DB_DRIVER
              value: "{{ .Values.database.driver }}"
            - name: DB_URL
              value: "{{ .Values.database.url }}"
            {{- if .Values.database.credentialsSecretEnabled }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.credentialsSecretName | default $fullName }}
                  key: {{ .Values.database.credentialsSecretKeys.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.credentialsSecretName | default $fullName }}
                  key: {{ .Values.database.credentialsSecretKeys.password }}
            {{- end }}
          {{- if .Values.extraEnvs }}
          {{- with tpl (toYaml .Values.extraEnvs) . }}
            {{ . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
            {{- if .Values.metrics.enabled }}
            - name: {{ .Values.metrics.service.portName }}
              containerPort: {{ .Values.metrics.service.port }}
              protocol: {{ .Values.metrics.service.protocol }}
            {{- end }}
          {{ if .Values.startupProbe.enabled -}}
          startupProbe:
            {{- toYaml .Values.startupProbe.config | nindent 12 }}
          {{- end }}
          {{ if .Values.readinessProbe.enabled -}}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.config | nindent 12 }}
          {{- end }}
          {{ if .Values.livenessProbe.enabled -}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.config | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ if eq (include "camunda-bpm-platform.withVolumes" .) "true" -}}
          volumeMounts:
            {{- if eq (include "camunda-bpm-platform.h2DatabaseIsUsed" .) "true" }}
            - name: {{ $fullName }}-database-h2
              mountPath: /camunda/camunda-h2-dbs
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
              {{- tpl (toYaml .Values.extraVolumeMounts) . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{ if eq (include "camunda-bpm-platform.withVolumes" .) "true" -}}
      volumes:
        {{- if eq (include "camunda-bpm-platform.h2DatabaseIsUsed" .) "true" }}
        - name: {{ $fullName }}-database-h2
          persistentVolumeClaim:
            claimName: {{ $fullName }}-database-h2
        {{- end -}}
        {{- if .Values.extraVolumes }}
          {{- tpl (toYaml .Values.extraVolumes) . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
