{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "camunda-bpm-platform.fullname" . }}
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - name: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}


  selector:
    {{- include "camunda-bpm-platform.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "camunda-bpm-platform.fullname" . }}-metrics
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "camunda-bpm-platform.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.metrics.service.port }}
    targetPort: {{ .Values.metrics.service.portName }}
    name: {{ .Values.metrics.service.portName }}
{{- end }}
